services:
  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    environment:
      TELEGRAM_API_ID: "${TELEGRAM_API_ID}"
      TELEGRAM_API_HASH: "${TELEGRAM_API_HASH}"
      TELEGRAM_LOCAL: "1"
    volumes:
      - data:/var/lib/telegram-bot-api
    ports:
      - 127.0.0.1:8081:8081
  markodownloadbot:
    image: mkevac/markodownloadbot:latest
    depends_on:
      - telegram-bot-api
    environment:
      TELEGRAM_BOT_API_TOKEN: "${TELEGRAM_BOT_API_TOKEN}"
    volumes:
      - data:/var/lib/telegram-bot-api

volumes:
  data:
